---
deployment:
  tasks:
    - export DEPLOYPATH=/home/thesolut/public_html/career-testing/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R jobs $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp logo.jpg $DEPLOYPATH
    - /bin/cp mail-handler.php $DEPLOYPATH